### ISSUE TITLE
[[Feature request]] add the possibility to change vim buffer's filetype.

### ISSUE THREAD

**Issue by yassinebridi** [raghur/vim-ghost#37]
Whenever i use vim-ghost i find myself writing markdown,
it would be much easier to change the filetype from txt to md by default,
since there is other tools that helps me write better with markdown that it is with txt.

**Comment by raghur** [comment]
this has been asked for before - see #19 
I've not wanted to set a single filetype since what works for one breaks for another... however, I think a decent compromise would be for me to just raise a user autocommand and people can customize what they want to do

```
augroup vim-ghost
au!
au User vim-ghost#connected  echom "got vim-ghost#connected: ". expand("%:a")

augroup END
```

1. you could just do a `set ft=markdown`
1. the buffer name can be passed in - so you can grep for domain name in it and set a per domain name filetype if you so wish...


I'll think I'll try this out this weekend...

**Comment by raghur** [comment]
Was a oneliner after all :) - Give this a shot and let me know.

**Comment by yassinebridi** [comment]
This is working perfectly, thanks @raghur for this beautiful plugin.
