### ISSUE TITLE
Does it work on vanilla vim?

### ISSUE THREAD

**Issue by kiteloopdesign** [raghur/vim-ghost#49]
First of all thanks for the plugin and super nice idea

You mention vim/nvim on the README and so I take it supports vim? I do however find this error that some other user has already reported on running it with plain vim (version 9 though)

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 03 2022 00:00:00)
Included patches: 1-828
```

Then when I open vim (after correctly installing vim-ghost: i can see it doing a ":verbose GhostInstall", all dependencies properly installed)

```
Error detected while processing /home/kitesutra/.vim/bundle/vim-ghost/plugin/vim_compat.vim:
line    5:
E117: Unknown function: yarp#py3
```

Seems to me this yarp function is a nvim thing?

There seems to be a fork of this project that does support vim, but I have not tried yet.

`https://github.com/pandysong/ghost-text.vim`

Any idea/suggestion welcome
Thanks

**Comment by raghur** [comment]
Sorry - I worked on vim compat at a time when I was using both vim and neovim; Now i've moved exclusively to neovim and I hear that vim 9 is breaking backward compat as well;

Even with vim 8 I need the YARP plugin to provide compatibility layer - likely that's broken due to same reasons... I just don't see myself installing vim and chasing this down.

If there's a fork that works with vim9 - please feel free to move to it... I'll update the docs to clarify vim 8 only sometime.
